### ISSUE TITLE
pose estimation demo runtime error

### ISSUE THREAD

**Issue by meghalD** [jimmyyhwu/pose-interpreter-networks#25]
While running demo.ipynb the following error comes up. I am unsure is it the sound card error or CUDA error ? Please help.

ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
found bundled python: /opt/blender/2.79/python
Import finished in 1.6221 sec.
Fra:1 Mem:56.16M (0.00M, Peak 64.88M) | Time:00:00.06 | Preparing Scene data
Fra:1 Mem:56.18M (0.00M, Peak 64.88M) | Time:00:00.06 | Preparing Scene data
Fra:1 Mem:56.18M (0.00M, Peak 64.88M) | Time:00:00.06 | Creating Shadowbuffers
Fra:1 Mem:56.18M (0.00M, Peak 64.88M) | Time:00:00.06 | Raytree.. preparing
Fra:1 Mem:91.02M (0.00M, Peak 91.02M) | Time:00:00.10 | Raytree.. building
Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Raytree finished
Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Creating Environment maps
Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Caching Point Densities
Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Sce: Scene Ve:126775 Fa:253749 La:1
Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Loading voxel datasets
Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Sce: Scene Ve:126775 Fa:253749 La:1
Fra:1 Mem:89.19M (0.00M, Peak 143.57M) | Time:00:01.00 | Sce: Scene Ve:126775 Fa:253749 La:1
Fra:1 Mem:89.19M (0.00M, Peak 143.57M) | Time:00:01.00 | Volume preprocessing
Fra:1 Mem:89.19M (0.00M, Peak 143.57M) | Time:00:01.00 | Sce: Scene Ve:126775 Fa:253749 La:1
Fra:1 Mem:89.19M (0.00M, Peak 143.57M) | Time:00:01.00 | Sce: Scene Ve:126775 Fa:253749 La:1
Fra:1 Mem:91.04M (0.00M, Peak 143.57M) | Time:00:01.32 | Scene, Part 13-20
Fra:1 Mem:91.46M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 3-20
Fra:1 Mem:91.37M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 11-20
Fra:1 Mem:91.30M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 9-20
Fra:1 Mem:91.21M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 7-20
Fra:1 Mem:91.48M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 19-20
Fra:1 Mem:91.46M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 15-20
Fra:1 Mem:91.05M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 5-20
Fra:1 Mem:91.05M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 18-20
Fra:1 Mem:91.44M (0.00M, Peak 143.57M) | Time:00:01.40 | Scene, Part 10-20
Fra:1 Mem:91.44M (0.00M, Peak 143.57M) | Time:00:01.41 | Scene, Part 1-20
Fra:1 Mem:91.44M (0.00M, Peak 143.57M) | Time:00:01.41 | Scene, Part 4-20
Fra:1 Mem:91.91M (0.00M, Peak 143.57M) | Time:00:01.42 | Scene, Part 17-20
Fra:1 Mem:91.82M (0.00M, Peak 143.57M) | Time:00:01.42 | Scene, Part 2-20
Fra:1 Mem:91.36M (0.00M, Peak 143.57M) | Time:00:01.43 | Scene, Part 14-20
Fra:1 Mem:90.95M (0.00M, Peak 143.57M) | Time:00:01.44 | Scene, Part 8-20
Fra:1 Mem:90.57M (0.00M, Peak 143.57M) | Time:00:01.45 | Scene, Part 12-20
Fra:1 Mem:90.19M (0.00M, Peak 143.57M) | Time:00:01.46 | Scene, Part 20-20
Fra:1 Mem:89.99M (0.00M, Peak 143.57M) | Time:00:01.49 | Scene, Part 16-20
Fra:1 Mem:89.28M (0.00M, Peak 143.57M) | Time:00:01.56 | Scene, Part 6-20
Fra:1 Mem:32.74M (0.00M, Peak 143.57M) | Time:00:01.57 | Compositing
Fra:1 Mem:32.74M (0.00M, Peak 143.57M) | Time:00:01.57 | Compositing | Determining resolution
Fra:1 Mem:32.74M (0.00M, Peak 143.57M) | Time:00:01.57 | Compositing | Initializing execution
Fra:1 Mem:34.21M (0.00M, Peak 143.57M) | Time:00:01.57 | Compositing | Tile 1-2
Fra:1 Mem:34.21M (0.00M, Peak 143.57M) | Time:00:01.58 | Compositing | Tile 2-2
Fra:1 Mem:34.20M (0.00M, Peak 143.57M) | Time:00:01.69 | Compositing | De-initializing execution
Fra:1 Mem:34.20M (0.00M, Peak 143.57M) | Time:00:01.69 | Sce: Scene Ve:126775 Fa:253749 La:1
Saved: '/tmp/tmpz3aqpi1j/render.png'
 Time: 00:01.75 (Saving: 00:00.05)

Blender quit
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "<stdin>", line 3, in visualize_batch
  File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/meghal/pose-interpreter-networks/pose_estimation/models.py", line 52, in forward
    x = self.resnet18(x)
  File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/meghal/pose-interpreter-networks/pose_estimation/models.py", line 199, in forward
    x = self.conv1(x)
  File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_MAPPING_ERROR

**Comment by meghalD** [comment]
> While running demo.ipynb the following error comes up. I am unsure is it the sound card error or CUDA error ? Please help.
> 
> ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
> ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
> AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
> found bundled python: /opt/blender/2.79/python
> Import finished in 1.6221 sec.
> Fra:1 Mem:56.16M (0.00M, Peak 64.88M) | Time:00:00.06 | Preparing Scene data
> Fra:1 Mem:56.18M (0.00M, Peak 64.88M) | Time:00:00.06 | Preparing Scene data
> Fra:1 Mem:56.18M (0.00M, Peak 64.88M) | Time:00:00.06 | Creating Shadowbuffers
> Fra:1 Mem:56.18M (0.00M, Peak 64.88M) | Time:00:00.06 | Raytree.. preparing
> Fra:1 Mem:91.02M (0.00M, Peak 91.02M) | Time:00:00.10 | Raytree.. building
> Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Raytree finished
> Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Creating Environment maps
> Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Caching Point Densities
> Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Sce: Scene Ve:126775 Fa:253749 La:1
> Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Loading voxel datasets
> Fra:1 Mem:89.18M (0.00M, Peak 143.57M) | Time:00:01.00 | Sce: Scene Ve:126775 Fa:253749 La:1
> Fra:1 Mem:89.19M (0.00M, Peak 143.57M) | Time:00:01.00 | Sce: Scene Ve:126775 Fa:253749 La:1
> Fra:1 Mem:89.19M (0.00M, Peak 143.57M) | Time:00:01.00 | Volume preprocessing
> Fra:1 Mem:89.19M (0.00M, Peak 143.57M) | Time:00:01.00 | Sce: Scene Ve:126775 Fa:253749 La:1
> Fra:1 Mem:89.19M (0.00M, Peak 143.57M) | Time:00:01.00 | Sce: Scene Ve:126775 Fa:253749 La:1
> Fra:1 Mem:91.04M (0.00M, Peak 143.57M) | Time:00:01.32 | Scene, Part 13-20
> Fra:1 Mem:91.46M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 3-20
> Fra:1 Mem:91.37M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 11-20
> Fra:1 Mem:91.30M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 9-20
> Fra:1 Mem:91.21M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 7-20
> Fra:1 Mem:91.48M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 19-20
> Fra:1 Mem:91.46M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 15-20
> Fra:1 Mem:91.05M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 5-20
> Fra:1 Mem:91.05M (0.00M, Peak 143.57M) | Time:00:01.39 | Scene, Part 18-20
> Fra:1 Mem:91.44M (0.00M, Peak 143.57M) | Time:00:01.40 | Scene, Part 10-20
> Fra:1 Mem:91.44M (0.00M, Peak 143.57M) | Time:00:01.41 | Scene, Part 1-20
> Fra:1 Mem:91.44M (0.00M, Peak 143.57M) | Time:00:01.41 | Scene, Part 4-20
> Fra:1 Mem:91.91M (0.00M, Peak 143.57M) | Time:00:01.42 | Scene, Part 17-20
> Fra:1 Mem:91.82M (0.00M, Peak 143.57M) | Time:00:01.42 | Scene, Part 2-20
> Fra:1 Mem:91.36M (0.00M, Peak 143.57M) | Time:00:01.43 | Scene, Part 14-20
> Fra:1 Mem:90.95M (0.00M, Peak 143.57M) | Time:00:01.44 | Scene, Part 8-20
> Fra:1 Mem:90.57M (0.00M, Peak 143.57M) | Time:00:01.45 | Scene, Part 12-20
> Fra:1 Mem:90.19M (0.00M, Peak 143.57M) | Time:00:01.46 | Scene, Part 20-20
> Fra:1 Mem:89.99M (0.00M, Peak 143.57M) | Time:00:01.49 | Scene, Part 16-20
> Fra:1 Mem:89.28M (0.00M, Peak 143.57M) | Time:00:01.56 | Scene, Part 6-20
> Fra:1 Mem:32.74M (0.00M, Peak 143.57M) | Time:00:01.57 | Compositing
> Fra:1 Mem:32.74M (0.00M, Peak 143.57M) | Time:00:01.57 | Compositing | Determining resolution
> Fra:1 Mem:32.74M (0.00M, Peak 143.57M) | Time:00:01.57 | Compositing | Initializing execution
> Fra:1 Mem:34.21M (0.00M, Peak 143.57M) | Time:00:01.57 | Compositing | Tile 1-2
> Fra:1 Mem:34.21M (0.00M, Peak 143.57M) | Time:00:01.58 | Compositing | Tile 2-2
> Fra:1 Mem:34.20M (0.00M, Peak 143.57M) | Time:00:01.69 | Compositing | De-initializing execution
> Fra:1 Mem:34.20M (0.00M, Peak 143.57M) | Time:00:01.69 | Sce: Scene Ve:126775 Fa:253749 La:1
> Saved: '/tmp/tmpz3aqpi1j/render.png'
> Time: 00:01.75 (Saving: 00:00.05)
> 
> Blender quit
> Traceback (most recent call last):
> File "", line 14, in
> File "", line 3, in visualize_batch
> File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
> return self.module(*inputs[0], **kwargs[0])
> File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/meghal/pose-interpreter-networks/pose_estimation/models.py", line 52, in forward
> x = self.resnet18(x)
> File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/meghal/pose-interpreter-networks/pose_estimation/models.py", line 199, in forward
> x = self.conv1(x)
> File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/meghal/python36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
> self.padding, self.dilation, self.groups)
> RuntimeError: CUDNN_STATUS_MAPPING_ERROR

It was some version issue with cuda. With torch 0.4 it was installing 0.4.0 and taking cuda 8 which was not working for the code. Later I installed torch 0.4.1 and it took cuda 9 as required. Finally the code works.
